export default {
  login: 'luongdao138',
  id: 80017680,
  node_id: 'MDQ6VXNlcjgwMDE3Njgw',
  avatar_url: 'https://avatars.githubusercontent.com/u/80017680?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/luongdao138',
  html_url: 'https://github.com/luongdao138',
  followers_url: 'https://api.github.com/users/luongdao138/followers',
  following_url:
    'https://api.github.com/users/luongdao138/following{/other_user}',
  gists_url: 'https://api.github.com/users/luongdao138/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/luongdao138/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/luongdao138/subscriptions',
  organizations_url: 'https://api.github.com/users/luongdao138/orgs',
  repos_url: 'https://api.github.com/users/luongdao138/repos',
  events_url: 'https://api.github.com/users/luongdao138/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/luongdao138/received_events',
  type: 'User',
  site_admin: false,
  name: 'Luongdao138',
  company: 'Hust Company',
  blog: 'https://www.facebook.com/profile.php?id=100040301135844',
  location: 'Van Thanh, Yen Thanh, Nghe An',
  email: null,
  hireable: null,
  bio: 'React Devepopers',
  twitter_username: 'LuongdaoHust',
  public_repos: 12,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-03-04T02:27:23Z',
  updated_at: '2021-03-28T05:14:09Z',
};
